Album.create(is_favorite: false, year: 1967, name: "Sgt. Pepper's Lonely Hearts Club Band", artist: Artist.find_or_create_by(name: "The Beatles"), condition: 'fair')
Album.create(is_favorite: true, year: 1966, name: "Pet Sounds", artist: Artist.find_or_create_by(name: "The Beach Boys"), condition: 'fair')
Album.create(is_favorite: true, year: 1966, name: "Revolver", artist: Artist.find_or_create_by(name: "The Beatles"), condition: 'fair')
Album.create(is_favorite: true, year: 1965, name: "Highway 61 Revisited", artist: Artist.find_or_create_by(name: "Bob Dylan"), condition: 'fair')
Album.create(is_favorite: true, year: 1965, name: "Rubber Soul", artist: Artist.find_or_create_by(name: "The Beatles"), condition: 'fair')
Album.create(is_favorite: true, year: 1971, name: "What's Going On", artist: Artist.find_or_create_by(name: "Marvin Gaye"), condition: 'fair')
Album.create(is_favorite: true, year: 1972, name: "Exile on Main St.", artist: Artist.find_or_create_by(name: "The Rolling Stones"), condition: 'fair')
Album.create(is_favorite: true, year: 1979, name: "London Calling", artist: Artist.find_or_create_by(name: "The Clash"), condition: 'fair')
Album.create(is_favorite: true, year: 1966, name: "Blonde on Blonde", artist: Artist.find_or_create_by(name: "Bob Dylan"), condition: 'fair')
Album.create(is_favorite: true, year: 1968, name: "The Beatles White Album", artist: Artist.find_or_create_by(name: "The Beatles"), condition: 'fair')
Album.create(is_favorite: true, year: 1976, name: "The Sun Sessions", artist: Artist.find_or_create_by(name: "Elvis Presley"), condition: 'fair')
Album.create(is_favorite: true, year: 1959, name: "Kind of Blue", artist: Artist.find_or_create_by(name: "Miles Davis"), condition: 'fair')
Album.create(is_favorite: false, year: 1967, name: "The Velvet Underground & Nico", artist: Artist.find_or_create_by(name: "The Velvet Underground"), condition: 'fair')
Album.create(is_favorite: true, year: 1969, name: "Abbey Road", artist: Artist.find_or_create_by(name: "The Beatles"), condition: 'fair')
Album.create(is_favorite: false, year: 1967, name: "Are You Experienced", artist: Artist.find_or_create_by(name: "The Jimi Hendrix Experience"), condition: 'fair')
Album.create(is_favorite: true, year: 1975, name: "Blood on the Tracks", artist: Artist.find_or_create_by(name: "Bob Dylan"), condition: 'fair')
Album.create(is_favorite: true, year: 1991, name: "Nevermind", artist: Artist.find_or_create_by(name: "Nirvana"), condition: 'fair')
Album.create(is_favorite: true, year: 1975, name: "Born to Run", artist: Artist.find_or_create_by(name: "Bruce Springsteen"), condition: 'fair')
Album.create(is_favorite: true, year: 1968, name: "Astral Weeks", artist: Artist.find_or_create_by(name: "Van Morrison"), condition: 'fair')
Album.create(is_favorite: true, year: 1982, name: "Thriller", artist: Artist.find_or_create_by(name: "Michael Jackson"), condition: 'fair')
Album.create(is_favorite: true, year: 1982, name: "The Great Twenty_Eight", artist: Artist.find_or_create_by(name: "Chuck Berry"), condition: 'fair')
Album.create(is_favorite: true, year: 1990, name: "The Complete Recordings", artist: Artist.find_or_create_by(name: "Robert Johnson"), condition: 'fair')
Album.create(is_favorite: true, year: 1970, name: "John Lennon/Plastic Ono Band", artist: Artist.find_or_create_by(name: "John Lennon / Plastic Ono Band"), condition: 'fair')
Album.create(is_favorite: true, year: 1973, name: "Innervisions", artist: Artist.find_or_create_by(name: "Stevie Wonder"), condition: 'fair')
Album.create(is_favorite: true, year: 1963, name: "Live at the Apollo, Album.create(is_favorite: true, year: 1962, name: ", artist: Artist.find_or_create_by(name: "James Brown"), condition: 'fair')
Album.create(is_favorite: false, year: 1977, name: "Rumours", artist: Artist.find_or_create_by(name: "Fleetwood Mac"), condition: 'fair')
Album.create(is_favorite: false, year: 1987, name: "The Joshua Tree", artist: Artist.find_or_create_by(name: "U2"), condition: 'fair')
Album.create(is_favorite: true, year: 1971, name: "Who's Next", artist: Artist.find_or_create_by(name: "The Who"), condition: 'fair')
Album.create(is_favorite: true, year: 1969, name: "Led Zeppelin", artist: Artist.find_or_create_by(name: "Led Zeppelin"), condition: 'fair')
Album.create(is_favorite: true, year: 1971, name: "Blue", artist: Artist.find_or_create_by(name: "Joni Mitchell"), condition: 'fair')
Album.create(is_favorite: true, year: 1965, name: "Bringing It All Back Home", artist: Artist.find_or_create_by(name: "Bob Dylan"), condition: 'fair')
Album.create(is_favorite: true, year: 1969, name: "Let It Bleed", artist: Artist.find_or_create_by(name: "The Rolling Stones"), condition: 'fair')
Album.create(is_favorite: true, year: 1976, name: "Ramones", artist: Artist.find_or_create_by(name: "Ramones"), condition: 'fair')
Album.create(is_favorite: true, year: 1968, name: "Music From Big Pink", artist: Artist.find_or_create_by(name: "The Band"), condition: 'fair')
Album.create(is_favorite: true, year: 1972, name: "The Rise and Fall of Ziggy Stardust and the Spiders From Mars", artist: Artist.find_or_create_by(name: "David Bowie"), condition: 'fair')
Album.create(is_favorite: true, year: 1971, name: "Tapestry", artist: Artist.find_or_create_by(name: "Carole King"), condition: 'fair')
Album.create(is_favorite: true, year: 1976, name: "Hotel California", artist: Artist.find_or_create_by(name: "Eagles"), condition: 'fair')
Album.create(is_favorite: true, year: 1963, name: "Please Please Me", artist: Artist.find_or_create_by(name: "The Beatles"), condition: 'fair')
Album.create(is_favorite: false, year: 1967, name: "Forever Changes", artist: Artist.find_or_create_by(name: "Love"), condition: 'fair')
Album.create(is_favorite: false, year: 1977, name: "Never Mind the Bollocks Here's the Sex Pistols", artist: Artist.find_or_create_by(name: "Sex Pistols"), condition: 'fair')
Album.create(is_favorite: false, year: 1967, name: "The Doors", artist: Artist.find_or_create_by(name: "The Doors"), condition: 'fair')
Album.create(is_favorite: true, year: 1973, name: "The Dark Side of the Moon", artist: Artist.find_or_create_by(name: "Pink Floyd"), condition: 'fair')
Album.create(is_favorite: true, year: 1975, name: "Horses", artist: Artist.find_or_create_by(name: "Patti Smith"), condition: 'fair')
Album.create(is_favorite: true, year: 1969, name: "The Band The Brown Album", artist: Artist.find_or_create_by(name: "The Band"), condition: 'fair')
Album.create(is_favorite: true, year: 1984, name: "Legend: The Best of Bob Marley and The Wailers", artist: Artist.find_or_create_by(name: "Bob Marley & The Wailers"), condition: 'fair')
Album.create(is_favorite: true, year: 1965, name: "A Love Supreme", artist: Artist.find_or_create_by(name: "John Coltrane"), condition: 'fair')
Album.create(is_favorite: true, year: 1988, name: "It Takes a Nation of Millions to Hold Us Back", artist: Artist.find_or_create_by(name: "Public Enemy"), condition: 'fair')
Album.create(is_favorite: true, year: 1971, name: "At Fillmore East", artist: Artist.find_or_create_by(name: "The Allman Brothers Band"), condition: 'fair')
Album.create(is_favorite: false, year: 1957, name: "Here's Little Richard", artist: Artist.find_or_create_by(name: "Little Richard"), condition: 'fair')
Album.create(is_favorite: true, year: 1970, name: "Bridge Over Troubled Water", artist: Artist.find_or_create_by(name: "Simon & Garfunkel"), condition: 'fair')
Album.create(is_favorite: true, year: 1964, name: "Meet The Beatles!", artist: Artist.find_or_create_by(name: "The Beatles"), condition: 'fair')
Album.create(is_favorite: true, year: 1991, name: "The Birth of Soul", artist: Artist.find_or_create_by(name: "Ray Charles"), condition: 'fair')
Album.create(is_favorite: true, year: 1968, name: "Electric Ladyland", artist: Artist.find_or_create_by(name: "The Jimi Hendrix Experience"), condition: 'fair')
Album.create(is_favorite: true, year: 1956, name: "Elvis Presley", artist: Artist.find_or_create_by(name: "Elvis Presley"), condition: 'fair')
Album.create(is_favorite: true, year: 1976, name: "Songs in the Key of Life", artist: Artist.find_or_create_by(name: "Stevie Wonder"), condition: 'fair')
Album.create(is_favorite: true, year: 1968, name: "Beggars Banquet", artist: Artist.find_or_create_by(name: "The Rolling Stones"), condition: 'fair')
Album.create(is_favorite: true, year: 1976, name: "Chronicle: The 20 Greatest Hits", artist: Artist.find_or_create_by(name: "Creedence Clearwater Revival"), condition: 'fair')
Album.create(is_favorite: true, year: 1969, name: "Trout Mask Replica", artist: Artist.find_or_create_by(name: "Captain Beefheart & His Magic Band"), condition: 'fair')
Album.create(is_favorite: false, year: 1987, name: "Appetite for Destruction", artist: Artist.find_or_create_by(name: "Guns N' Roses"), condition: 'fair')
Album.create(is_favorite: true, year: 1991, name: "Achtung Baby", artist: Artist.find_or_create_by(name: "U2"), condition: 'fair')
Album.create(is_favorite: true, year: 1971, name: "Sticky Fingers", artist: Artist.find_or_create_by(name: "The Rolling Stones"), condition: 'fair')
Album.create(is_favorite: true, year: 1970, name: "Moondance", artist: Artist.find_or_create_by(name: "Van Morrison"), condition: 'fair')
Album.create(is_favorite: true, year: 1979, name: "Off the Wall", artist: Artist.find_or_create_by(name: "Michael Jackson"), condition: 'fair')
Album.create(is_favorite: true, year: 1971, name: "[Led Zeppelin IV]", artist: Artist.find_or_create_by(name: "Led Zeppelin"), condition: 'fair')
Album.create(is_favorite: false, year: 1977, name: "The Stranger", artist: Artist.find_or_create_by(name: "Billy Joel"), condition: 'fair')
Album.create(is_favorite: true, year: 1986, name: "Graceland", artist: Artist.find_or_create_by(name: "Paul Simon"), condition: 'fair')
Album.create(is_favorite: true, year: 1972, name: "Superfly", artist: Artist.find_or_create_by(name: "Curtis Mayfield"), condition: 'fair')
Album.create(is_favorite: true, year: 1975, name: "Physical Graffiti", artist: Artist.find_or_create_by(name: "Led Zeppelin"), condition: 'fair')
Album.create(is_favorite: true, year: 1970, name: "After the Gold Rush", artist: Artist.find_or_create_by(name: "Neil Young"), condition: 'fair')
Album.create(is_favorite: true, year: 1991, name: "Star Time", artist: Artist.find_or_create_by(name: "James Brown"), condition: 'fair')
Album.create(is_favorite: true, year: 1984, name: "Purple Rain", artist: Artist.find_or_create_by(name: "Prince and the Revolution"), condition: 'fair')
Album.create(is_favorite: true, year: 1980, name: "Back in Black", artist: Artist.find_or_create_by(name: "AC/DC"), condition: 'fair')
Album.create(is_favorite: true, year: 1965, name: "Otis Blue: Otis Redding Sings Soul", artist: Artist.find_or_create_by(name: "Otis Redding"), condition: 'fair')
Album.create(is_favorite: true, year: 1969, name: "Led Zeppelin II", artist: Artist.find_or_create_by(name: "Led Zeppelin"), condition: 'fair')
Album.create(is_favorite: true, year: 1971, name: "Imagine", artist: Artist.find_or_create_by(name: "John Lennon"), condition: 'fair')
Album.create(is_favorite: false, year: 1977, name: "The Clash", artist: Artist.find_or_create_by(name: "The Clash"), condition: 'fair')
Album.create(is_favorite: true, year: 1972, name: "Harvest", artist: Artist.find_or_create_by(name: "Neil Young"), condition: 'fair')
Album.create(is_favorite: false, year: 1967, name: "Axis: Bold as Love", artist: Artist.find_or_create_by(name: "The Jimi Hendrix Experience"), condition: 'fair')
Album.create(is_favorite: false, year: 1967, name: "I Never Loved a Man the Way I Love You", artist: Artist.find_or_create_by(name: "Aretha Franklin"), condition: 'fair')
Album.create(is_favorite: true, year: 1968, name: "Lady Soul", artist: Artist.find_or_create_by(name: "Aretha Franklin"), condition: 'fair')
Album.create(is_favorite: true, year: 1984, name: "Born in the U.S.A.", artist: Artist.find_or_create_by(name: "Bruce Springsteen"), condition: 'fair')
Album.create(is_favorite: true, year: 1979, name: "The Wall", artist: Artist.find_or_create_by(name: "Pink Floyd"), condition: 'fair')
Album.create(is_favorite: true, year: 1968, name: "At Folsom Prison", artist: Artist.find_or_create_by(name: "Johnny Cash"), condition: 'fair')
Album.create(is_favorite: true, year: 1969, name: "Dusty in Memphis", artist: Artist.find_or_create_by(name: "Dusty Springfield"), condition: 'fair')
Album.create(is_favorite: true, year: 1972, name: "Talking Book", artist: Artist.find_or_create_by(name: "Stevie Wonder"), condition: 'fair')
Album.create(is_favorite: true, year: 1973, name: "Goodbye Yellow Brick Road", artist: Artist.find_or_create_by(name: "Elton John"), condition: 'fair')
Album.create(is_favorite: true, year: 1978, name: "20 Golden Greats", artist: Artist.find_or_create_by(name: "Buddy Holly"), condition: 'fair')
Album.create(is_favorite: false, year: 1987, name: "Sign Peace the Times", artist: Artist.find_or_create_by(name: "Prince"), condition: 'fair')
Album.create(is_favorite: true, year: 1984, name: "40 Greatest Hits", artist: Artist.find_or_create_by(name: "Hank Williams"), condition: 'fair')
Album.create(is_favorite: true, year: 1970, name: "Bitches Brew", artist: Artist.find_or_create_by(name: "Miles Davis"), condition: 'fair')
Album.create(is_favorite: true, year: 1969, name: "Tommy", artist: Artist.find_or_create_by(name: "The Who"), condition: 'fair')
Album.create(is_favorite: true, year: 1963, name: "The Freewheelin' Bob Dylan", artist: Artist.find_or_create_by(name: "Bob Dylan"), condition: 'fair')
Album.create(is_favorite: true, year: 1978, name: "This is_favorite: true, Year's Model", artist: Artist.find_or_create_by(name: "Elvis Costello"), condition: 'fair')
Album.create(is_favorite: true, year: 1971, name: "There's a Riot Goin' On", artist: Artist.find_or_create_by(name: "Sly & The Family Stone"), condition: 'fair')
